### ISSUE TITLE
repo reorganization & cleanup plan

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/FRFR-analyses#4]
Once we've collected the last of the data, we'll want to do a final organization and cleaning up of this repo.  Some initial thoughts on things to take care of:

Transcription branch:
- could make a separate repo for the notebooks, transcription data, and analyses that live here
- could make a directory within this repo for all AutoFR "stuff"

fingerprint-analyses branch:
- this has the notebooks with the most up-to-date analyses.  Will probably want to merge into master eventually

working branch:
- outdated, doesn't contain anything master doesn't have.  Can either be merged or deleted

El-presentation-figures directory (fingerprint-analyses branch):
- this can be deleted

data directory:
- "encoding" subdirectory includes old `participants.db` files.  Should be updated before releasing
- "recall" subdirectory includes transcriptions of recall data, sorted by test room, by subject IDs.  Should be updated before releasing

eggs directory (fingerprint-analyses branch):
- should be added to master via merge
- contains egg for each exp version.  
- confirm each egg has all subjects for experiment version before releasing
- settle on naming convention.  Current one is expX.X_egg.p.  Rename for manipulation?
- should delete "PreviousEggs" subdirectory

etc directory:
- contains outdated transcriptions and db files
- should delete before releasing

figures directory:
- should ultimately be the home of figures used in paper upon release
- move contents of notebooks>figs subdirectory here

notebooks directory (fingerprint-analyses branch is most up-to-date):
- merge into master
- should clean up notebook readability
- for notebooks whose analyses were not ultimately used: move to etc subdirectory or delete?
- weekly test room report notebooks still run on pyrec.  Update to quail? 
- move participants.db file (after updating post-data collection) to data directory
- put contents of "PDF" subdirectory in "figures" directory
- comb through "figs" subdirectory, keep up-to-date figures, move them to figures directory
- potentially combine notebooks by analysis type? Basic, variability-based, other

scripts directory
- determine usefulness of el-report-generator, and if it can be replaced by weekly-report notebooks

stimuli directory
- contains cut_wordpool.csv file
- no modification necessary

Other tasks:
- make sure requrements.txt is up to date
- make sure README.md contains necessary information & is up to date
- delete `testfile.txt` and `testfile2.txt`.  Both are empty text files.
- fix pandas compatibility with versions >0.18.0

**Comment by jeremymanning** [comment]
closing!
